name: um-tools CI
run-name: ${{ github.actor }} pushes to ${{ github.event.repository.name }}/${{ github.ref }}

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Run Maven Build
        run: mvn -B clean package --file pom.xml

      - name: Run Checkstyle (Code Style Analysis)
        run: mvn checkstyle:check

      - name: Run PMD (Static Code Analysis)
        run: mvn pmd:check

      - name: Run SpotBugs (Bug Detection)
        run: mvn spotbugs:check
