name: um-tools CI
run-name: ${{ github.actor }} pushes to ${{ github.event.repository.name }}/${{ github.ref }}

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Validate Project Structure and Dependencies
        run: mvn -B validate --file pom.xml

      - name: Build Maven Package
        run: mvn -B clean package --file pom.xml

      - name: Verify Build and Run Tests
        run: mvn -B verify --file pom.xml
